### ISSUE TITLE
AsciidoctorJ PDF fails on Windows since 1.5.0-alpha.10

### ISSUE THREAD

**Issue by antoinesd** [asciidoctor/asciidoctorj#416] opened 2016-01-07 13:54 UTC
My co-author and I are using Asciidoctor Maven plugin and Asciidoctorj-pdf to generate html and pdf version of our book.

I'm working on MacOS and had no problem to upgrade to Asciidoctor Maven plugin 1.5.3 and AsciidoctorJ 1.5.0-alpha.11.

My co-author is using windows 10 and have the following crash when generating pdf with these versions:

````
Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc (generate-pdf-doc) on project book:
Execution generate-pdf-doc of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed:
(Errno::ENOENT) D:/maven/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.10.1/asciidoctorj-pdf-1.5.0-alpha.10.1.jar!D:/gems/addressable-2.3.8/data/unicode.data -> [Help 1]

````

When reverting to Mvn plugin 1.5.2.1 and AsciidoctorJ 1.5.0-alpha.9 generation is ok.

I reproduced the problem on windows 8.1 VM on my machine. 
I'm not sure if it comes from Maven plugin or AsciidoctorJ. Sorry if I'm in the wrong place.

**Comment by robertpanzer** [comment] 2016-01-07 14:26
Hi Antoine,

I think you are seeing this issue with JRuby 1.7.23 on Windows: https://github.com/jruby/jruby/issues/3496

I hope that it works if you go back to the version used by asciidoctorj, 1.7.21.
That is, please configure the asciidoctor-maven-plugin like this:
```xml
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
                <version>1.5.3</version>
                <dependencies>
                    <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctorj-pdf</artifactId>
                        <version>1.5.0-alpha.10.1</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jruby</groupId>
                        <artifactId>jruby-complete</artifactId>
                        <version>1.7.21</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <backend>pdf</backend>
                </configuration>
            </plugin>
```

As there are new versions available of asciidoctor and asciidoctor-pdf you might even want to upgrade to the new versions:
```xml
            <plugin>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctor-maven-plugin</artifactId>
                <version>1.5.3</version>
                <dependencies>
                    <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctorj</artifactId>
                        <version>1.5.4</version>
                    </dependency>
                    <dependency>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctorj-pdf</artifactId>
                        <version>1.5.0-alpha.11</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jruby</groupId>
                        <artifactId>jruby-complete</artifactId>
                        <version>1.7.21</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <backend>pdf</backend>
                </configuration>
            </plugin>
```

Cheers
Robert

**Comment by abelsromero** [comment] 2016-01-07 14:50
I guess we should revert the maven-plugin to 1.7.21 too until the issue is fixed.

Also, I just noticed the [example](https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-pdf-example) uses v 9.0.4.0 and works fine.

**Comment by robertpanzer** [comment] 2016-01-07 14:55
Hi Abel,

I would recommend sticking with 1.7.21 at the moment.
Unfortunately JRuby doesn't have very much luck at the moment on Windows and also 9.0.4.0 has its issues: https://github.com/jruby/jruby/issues/3473

Upgrading the JRuby dependency should rather be an option if you know you're not going to run on Windows instead of requiring to downgrade.

Cheers
Robert

**Comment by antoinesd** [comment] 2016-01-08 08:23
Hi Robert,
Reverting to JRuby 1.7.21 worked. Thanks a lot for your help.

**Comment by mojavelinux** [comment] 2016-01-08 08:26
That's good news.

We really need to let the JRuby folks know that the lack of Windows testing is really presenting quite a problem for the community.

On the other hand, we could do a better job of testing on Windows so that we pick JRuby versions that work :) Let's be sure to not just upgrade for upgrade sake.

**Comment by robertpanzer** [comment] 2016-01-11 09:21
I think we can close this issue, as it was related to the asciidoctor-maven-plugin.

**Closed by robertpanzer** 2016-01-11 09:21 UTC

**Comment by abelsromero** [comment] 2016-01-11 09:25
It's been already fixed for the new release (https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/191)

**Comment by robertpanzer** [comment] 2016-01-11 09:26
:+1:

Am Montag, 11. Januar 2016 schrieb Abel Salgado Romero :

**Comment by slaskawi** [comment] 2016-07-20 07:53
Hey! 

Could you please tell me when do you plan a release with this fix?

Thanks!
Sebastian

**Comment by abelsromero** [comment] 2016-07-20 08:11
The fix updates the jruby version used by default, but you can just replace it in your pom adding the dependency in the plugin configuration.
Here is an example:
https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoc-to-html-example/pom.xml#L27-L31

**Comment by slaskawi** [comment] 2016-07-20 08:15
Thanks @abelsromero! Fortunately Windows builds are not top priority for us so we can just wait for another version :)
