### ISSUE TITLE
Update asciidoctorj-diagram to use asciidoctor-diagram 1.5.0

### ISSUE THREAD

**Issue by ClausRoh** [asciidoctor/asciidoctorj#473] opened 2016-06-27 08:09 UTC
There is an issue in the  asciidoctor-diagram regarding relative paths in PlantUML !include directives which is fixed in the asciidoctor-diagram 1.5.0.. See
https://github.com/asciidoctor/asciidoctor-diagram/issues/116. 

Can you please make and publish a new build of the maven plugin that includes this fix.

**Comment by pepijnve** [comment] 2016-06-29 12:20
Duplicate of #462

**Comment by pepijnve** [comment] 2016-06-29 12:22
@robertpanzer is there anything specific holding this back? I did quick test locally and it seems updating the version in the gradle.properties, building and publishing is all that's necessary.
The 1.5.0 build hasn't propagated to the torquebox proxy yet it seems so I couldn't test that yet. Test passes with 1.4.0 without any asciidoctorj code changes.

**Comment by robertpanzer** [comment] 2016-06-29 13:53
Currently we release the extension projects like the diagram extension or the PDF or EPUB3 converter together with AsciidoctorJ.
That makes the current distribution contain all the latest extensions.

I can certainly do a release of asciidoctorj-diagram 1.5.0.
Question is should we also make a release of AsciidoctorJ? And if so with which version? 1.5.4.1?
Or should we simply release asciidoctorj-diagram alone?

@mojavelinux: Do you have thoughts on this?

Cheers
Robert

**Comment by pepijnve** [comment] 2016-06-29 14:03
What do you mean with 'current distribution'? There doesn't seem to be an artefact (or pom only meta package) that depends on all other artefacts.
Afaict asciidoctorj-diagram depends on asciidoctorj but not vice versa. If that's correct then I don't think there's a need to couple the release process of the two.

**Comment by robertpanzer** [comment] 2016-06-29 14:07
Hi Pepjin,

with every release of AsciidoctorJ there is also a distribution as a zip that you can download and start AsciidoctorJ from the command line:
Here you can see the zip: http://repo1.maven.org/maven2/org/asciidoctor/asciidoctorj/1.5.4/ <http://repo1.maven.org/maven2/org/asciidoctor/asciidoctorj/1.5.4/>
This zip contains everything needed, including jruby etc.

You’re right with the dependencies, nevertheless we publish the zip with the same GAV as asciidoctorj.

Cheers
Robert

**Comment by ClausRoh** [comment] 2016-06-30 12:48
@robertpanzer for me it would be really helpful if you could release an asciidoctorj-diagram 1.5.0 with the  asciidoctor-diagram 1.5.0 (https://rubygems.org/gems/asciidoctor-diagram/versions/1.5.0). Would this version work together with AsciidoctorJ 1.5.4 or do we need a newer AsciidoctorJ  version?

**Comment by mojavelinux** [comment] 2016-06-30 22:17
I want to emphasize that we have plans to split AsciidoctorJ into separate repositories, one repository per gem, so that we can keep these releases in sync and possibly automate them. What we are observing here is exactly the problem that led us to that decision. We just haven't made that switch yet.

As for the distribution...I think that also needs to be a separate repository with its own version. In the future, we don't want the distribution number to correspond to an Asciidoctor core number or else it gets coupled to the Asciidoctor core release.

This is what we've learned :) Now we just need to get there.

**Comment by ClausRoh** [comment] 2016-07-05 06:20
@mojavelinux that sounds good, but until you are there could't you just a release a new asciidoctor-diagram 1.5.0? The fix would be really helpful for me.

**Comment by mojavelinux** [comment] 2016-07-05 06:21
I think @robertpanzer is planning to do that as part of the AsciidoctorJ 1.5.4.1 release.

**Comment by robertpanzer** [comment] 2016-07-05 06:23
Yep, will go for it over the weekend.
I don't think I'll get earlier to it this week.

**Comment by ClausRoh** [comment] 2016-07-05 06:27
Great. Thanks a lot!

**Closed** 2016-07-08 19:49 UTC

**Comment by ClausRoh** [comment] 2016-07-13 13:28
@robertpanzer @pepijnve 
I managed to update my project to the following versions:
...
 <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <asciidoctor.maven.version>1.5.3</asciidoctor.maven.version>
        <asciidoctorj.version>1.5.4.1</asciidoctorj.version>
        <asciidoctorj.diagram.version>1.5.0</asciidoctorj.diagram.version>
        <asciidoctorj.pdf.version>1.5.0-alpha.11</asciidoctorj.pdf.version>
        <jruby.version>1.7.25</jruby.version>
    </properties>
...
 <plugin>
                    <groupId>org.asciidoctor</groupId>
                    <artifactId>asciidoctor-maven-plugin</artifactId>
                    <version>${asciidoctor.maven.version}</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.jruby</groupId>
                            <artifactId>jruby-complete</artifactId>
                            <version>${jruby.version}</version>
                        </dependency>                     
                        <dependency>
                            <groupId>org.asciidoctor</groupId>
                            <artifactId>asciidoctorj</artifactId>
                            <version>${asciidoctorj.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>org.asciidoctor</groupId>
                            <artifactId>asciidoctorj-diagram</artifactId>
                            <version>${asciidoctorj.diagram.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>org.asciidoctor</groupId>
                            <artifactId>asciidoctorj-pdf</artifactId>
                            <version>${asciidoctorj.pdf.version}</version>
                        </dependency>
                    </dependencies>
...

Diagrams without any includes seems to work as before.
But as soon as I have an !include directive I get the following error in the output:

**Failed to generate image: uninitialized constant Asciidoctor::Diagram::PlantUml::URI**

I get this error even if the file I want to include doesn't even exist. 
Do you have any idea how I can solve this error?
As it looks now no !include directive (even with a full path) is working, or am I missing something?

Any help would be greatly appreciated!

**Comment by pepijnve** [comment] 2016-07-13 13:30
That's an error in the code. Bizarre that this wasn't picked up by the unit tests.

**Comment by pepijnve** [comment] 2016-07-13 13:34
There's a `require 'uri'` statement missing in the plantuml code. RSpec (or something else) is probably requiring it when the unit tests run. Sorry about this; I'll fix this right away and build 1.5.1. Will require another asciidoctorj-diagram build I'm afraid.
As a workaround, if you can require 'uri' somewhere else externally then the problem should be fixed.

**Comment by robertpanzer** [comment] 2016-07-13 13:46
Depending on how the document is rendered this is easily possible.
From the command line that should be `asciidoctorj -r uri -r asciidoctor-diagram my.adoc`.
And with the asciidoctor-maven-plugin it's simply 
```
            <configuration>
              <requires>
                <require>uri</require>
                <require>asciidoctor-diagram</require>
              </requires>
...
```

**Comment by pepijnve** [comment] 2016-07-13 14:09
@ClausRoh Logged this as https://github.com/asciidoctor/asciidoctor-diagram/issues/119, fixed and release 1.5.1. Apologies for the inconvenience.

**Comment by ClausRoh** [comment] 2016-07-14 05:49
@robertpanzer @pepijnve 

Thank you for your help.
<require>uri</require>
seems to solve this issue.

However it is still not working as (I) expected.
As it looks now, the include path is relative to the path of the *.adoc file and not relative to
the puml file that is including the other one.

But if the *.puml files are in another directory than the adoc file it is not working.
If there is, for example a Testdocument.adoc inside c:\temp
c:\temp\Testdocument.adoc
and  the puml files SimpleIncludedFile.puml and SimpleIncludeTest.puml inside c:\temp\puml\
c:\temp\puml\SimpleIncludedFile.puml
c:\temp\puml\SimpleIncludeTest.puml

If the Testdocument.adoc includes the  SimpleIncludeTest.puml with include::puml/SimpleIncludeTest.puml[]
and the SimpleIncludeTest includes the  SimpleIncludedFile.puml with !include SimpleIncludedFile.puml!0 (or !include ./SimpleIncludedFile.puml!0)
then after generating the adoc output with the maven plugin I get an error 
"cannot include c:\temp\SimpleIncludedFile.puml".

I can add the sub directory to the include directive like "!include ./puml/SimpleIncludedFile.puml!0" to get 
the adoc rendering correctly, but then i can't use any puml editor/renderer (e.g. the puml eclipse plugin) because
they (of course) do not know of the sub directory.

Am I doing something wrong, or is this still a bug?

**Comment by pepijnve** [comment] 2016-07-14 07:25
That's odd; I have a test case for exactly that type of configuration. When you use inline plantuml blocks in your document the paths are indeed resolved wrt the adoc file itself. When you use the block macro though it should be done relative the the puml file.
I'll create an issue for this in the asciidoctor-diagram project so we can track work on this there.
