### ISSUE TITLE
Asciidoctor rendering fails when using Java extensions

### ISSUE THREAD

**Issue by pmagon** [asciidoctor/asciidoctorj#267] opened 2015-01-12 13:35 UTC
It seems that there is still a problem (I tried with 1.5.2...)
With TerminalCommandTreeprocessor:

    Hello World

    $ echo "Hello, World!"

    = Title

    $ gem install asciidoctor

By using asciidoctor.convert I get

    Exception in thread "main" java.lang.ClassCastException: org.asciidoctor.ast.SectionImpl cannot be    cast to org.jruby.RubyObject
    at org.asciidoctor.ast.AbstractBlockImpl.blocks(AbstractBlockImpl.java:52)
    at com.imtf.test.asciidoc.TestAsciiDoc.showDoc(TestAsciiDoc.java:301)
    at com.imtf.test.asciidoc.TestAsciiDoc.test6(TestAsciiDoc.java:343)
    at com.imtf.test.asciidoc.TestAsciiDoc.main(TestAsciiDoc.java:362)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

I also have similar errors with the "gistMacro" and "ManpageMacro" examples:

    = Hello
    Test

    == Sect 2

    gist::1234[]
 
Result:

    Exception in thread "main" java.lang.ClassCastException: org.jruby.gen.InterfaceImpl1503916182 cannot be cast to org.jruby.RubyObject
	at org.asciidoctor.ast.AbstractBlockImpl.blocks(AbstractBlockImpl.java:52)
	at com.imtf.test.asciidoc.TestAsciiDoc.showDoc(TestAsciiDoc.java:301)
	at com.imtf.test.asciidoc.TestAsciiDoc.test6(TestAsciiDoc.java:343)
	at com.imtf.test.asciidoc.TestAsciiDoc.main(TestAsciiDoc.java:362)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

by combining TreeProcessor and BlockMacroProcessor I get:

    Exception in thread "main" org.jruby.exceptions.RaiseException: (TypeError) exception class/object expected
	at RUBY.load(/opt/repository/org/asciidoctor/asciidoctorj/1.5.2/asciidoctorj-1.5.2.jar!/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1362)
	at RUBY.load(<script>:80)
	at org.jruby.gen.InterfaceImpl1277167653.load(org/jruby/gen/InterfaceImpl1277167653.gen:13)

I'm not into ruby, cannot help much, sorry :(

**Comment by lordofthejars** [comment] 2015-01-12 13:53
It seems a similar problem we found with Converter but for extensions, we would need to see what is the RubyObject type it is returning. Thanks for helping on improving this. 

BTW probably the problem is on Java part.

**Comment by lordofthejars** [comment] 2015-03-09 09:50
I have tried today with asciidcotorj 1.6.0 branch and they work. So with the reworking of extensions mechanism this problems has been solved.

**Comment by mojavelinux** [comment] 2015-04-01 19:24
:beers:

**Comment by pmagon** [comment] 2015-04-16 08:35
I try to test with 1.6.0 SNAPSHOT but I have a very strange problem...
I get 

    Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "main" 

My code:

    System.out.println ("CREATE");
    Asciidoctor asciidoctor = JRubyAsciidoctor.create ();
    System.out.println ("OK");

The second "System.out.println" breaks.... It seems that "System.out" has been changed on "create"
If I save and restore "System.out" after the call I get the same error on "asciidoctor.convertFiles"...

BTW: the version in "gradle.properties" is 1.5.3-SNAPSHOT (supposed to be 1.6.0-SNAPSHOT ?)
Thanks

**Comment by lordofthejars** [comment] 2015-04-16 08:38
Well Gradle numbering is different from AsciidoctorJ.  I am not sure why this is happening to you.

**Comment by robertpanzer** [comment] 2015-04-16 09:19
@lordofthejars I think the StackOverflow comes from here:
https://github.com/asciidoctor/asciidoctorj/blob/asciidoctorj-1.6.0/asciidoctorj-core%2Fsrc%2Fmain%2Fjava%2Forg%2Fasciidoctor%2Finternal%2FJRubyAsciidoctor.java#L40

This is what we already discussed about.
It does not occur in the gradle tests because Gradle injects its own JUL Logger which breaks the cycle between catching System.out and forwarding it to the default ConsoleHandler which again does a System.out. :smiley:

**Comment by pmagon** [comment] 2015-04-17 11:52
I did the same test with 1.6.0-SNAPSHOT (from the branch 1.6.0, the generated jar is 1.5.3-SNAPSHOT ?).
I don't get any exception.
However, the following doesn't work:

    = Title
    Hello World
    
    $ echo "Hello, World!"
    
    == Title 2
    
    $ gem install asciidoctor   

The "Terminal command" is not rendered... If I remove "Title 2" it works.

**Comment by robertpanzer** [comment] 2015-04-17 12:50
This behavior is normal if you change the document like this.
(I guess you use the TerminalCommandTreeProcessor from the test suite.)

This tree processor only iterates the top level blocks of the document tree.
And with your document changes it will only see 
- a block containing a block that is the paragraph $ echo ...
- and a section containing a block that is the paragraph $ gem install

But the processor does not recurse into the top level blocks so it doesn't handle the paragraphs on the second level.

The processor could be fixed by simply replacing the current process method by:

```
    @Override
    public DocumentRuby process(DocumentRuby document) {
    	this.document = document;
        processBlock((AbstractBlock) this.document);
        return this.document;
    }

    private void processBlock(AbstractBlock block) {

        List<AbstractBlock> blocks = block.getBlocks();

        for (int i = 0; i < blocks.size(); i++) {
            final AbstractBlock currentBlock = blocks.get(i);
            if(currentBlock instanceof AbstractBlock) {
                if ("paragraph".equals(currentBlock.getContext())) {
                    List<String> lines = ((Block) currentBlock).lines();
                    if (lines.size() > 0 && lines.get(0).startsWith("$")) {
                        blocks.set(i, convertToTerminalListing((Block) currentBlock));
                    }
                } else {
                    // It's not a paragraph, so recursively descent into the child node
                    processBlock(currentBlock);
                }
            }
        }
    }
```

**Comment by pmagon** [comment] 2015-04-17 13:46
Thanks ! perfect... However, I now have a side effect with the "BlockMacroProcessor"  (eg: "gis macro"):
By adding "gist::123[]" to the end of the document, I get an exception:

    SEVERE: (TypeError) exception class/object expected
    Exception in thread "main" org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (TypeError) exception class/object expected
    ...
    Caused by: org.jruby.exceptions.RaiseException: (TypeError) exception class/object expected
	at RUBY.load(/mnt/d2/repository/org/asciidoctor/asciidoctorj/1.6.0-SNAPSHOT/asciidoctorj-1.6.0-SNAPSHOT.jar!/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1362)
	at RUBY.convert(/mnt/d2/repository/org/asciidoctor/asciidoctorj/1.6.0-SNAPSHOT/asciidoctorj-1.6.0-SNAPSHOT.jar!/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1458)
	at RUBY.convert_file(/mnt/d2/repository/org/asciidoctor/asciidoctorj/1.6.0-SNAPSHOT/asciidoctorj-1.6.0-SNAPSHOT.jar!/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1562)
	at RUBY.convertFile(<script>:68)
	at org.jruby.gen.InterfaceImpl231735525.convertFile(org/jruby/gen/InterfaceImpl231735525.gen:13)    

Without using your code, the block macro is rendered (but not the "terminal command"...)

Is it acceptable to have several processors (extentions) ?

Thanks again !

**Comment by robertpanzer** [comment] 2015-04-17 14:22
I am unsure about this, but there is at least one test at the moment that is ignored saying it is not possible to register to block extensions.
Maybe the behavior you see is related to this.

https://github.com/asciidoctor/asciidoctorj/blob/asciidoctorj-1.6.0/asciidoctorj-core/src/test/java/org/asciidoctor/extension/WhenExtensionIsRegisteredAsService.java#L32

**Comment by robertpanzer** [comment] 2015-05-06 12:49
Strange.
I just tried adding the TerminalCommandTreeProcessor and the GistMacro and it works.
I uploaded that to https://github.com/robertpanzer/asciidoctorj/tree/267_MultipleExtensions
Could you take a look if you do sth different?

@lordofthejars Do you think it would be worth adding the new test to AsciidoctorJ? That is: https://github.com/robertpanzer/asciidoctorj/commit/3646ebc89e059832c1cff214442ab48dc9ef26f1

**Comment by lordofthejars** [comment] 2015-05-06 13:04
Absolutely! I think there are no tests about using more than one extension at once, so I think it would be a really good addition to test suite.  :+1:

**Comment by pmagon** [comment] 2015-05-06 14:42
Robert,
I tried with your branch and it fails:

    Unknown content model 'attributes' for block: #<Asciidoctor::Block@2004 {context: :pass, content_model: :attributes, style: nil, lines: 1}>

No stacktrace (I think it comes from System.err...)

If I remove the GistMacro from sample-with-terminal-command-and-gist-macro.ad,
it works...

Note: I still have to comment "System.out"  and "System.err" redirections... (StackOverflow...)

**Comment by robertpanzer** [comment] 2015-05-06 15:02
Strange, the test even runs on Travis and Appveyor, see #298.
(With the AsciidoctorJ 1.6.0 branch!)

**Comment by robertpanzer** [comment] 2015-05-06 15:05
> Note: I still have to comment "System.out" and "System.err" redirections... (StackOverflow...)

@pmagon Could you please file an issue for that?

**Comment by robertpanzer** [comment] 2015-05-06 15:16
@pmagon Do you have another GistMacro? 
Your new error message looks like if the config of the processor is passed to createBlock, see GistMacro in https://github.com/asciidoctor/asciidoctorj/commit/1b6f4397032baa4347b83b40e117f70d39b08f78
Instead the process methodshould simply look like:

    public Block process(AbstractBlock parent, String target, Map<String, Object> attributes) {
       
       String content = "<div class=\"content\">\n" + 
       		"<script src=\"https://gist.github.com/"+target+".js\"></script>\n" + 
       		"</div>"; 
       
       return createBlock(parent, "pass", Arrays.asList(content), attributes); // No more this.getConfig() as additional parameter!
    }

**Comment by pmagon** [comment] 2015-05-06 15:29
Robert, you are right !
I was using the old code... it works !

Thanks !

I will file an issue for the StackOverflow...

**Comment by robertpanzer** [comment] 2015-05-06 15:38
Awesome!
So we can close the issue with 1.6.0?

**Comment by pmagon** [comment] 2015-05-06 16:18
I did some extra tests and combined with other extensions...
Perfect for me !! 
:+1: 

Thanks

**Comment by mojavelinux** [comment] 2015-05-06 20:53
Great news! Tests save the day again :)

**Comment by bladnor** [comment] 2015-07-09 09:38
I'm not sure if this belongs to asciidoctorj or to the asciidoctor-maven-plugin issue list.
I would like to use the Treeprocessor. From the docs I read that the configuration in the maven pom should look like mentioned below. But when I run it I get the follwoing Error:
```
failed: (ArgumentError) asciidoctor: FAILED: D:/devsbb/workspaces/mca2esta/mca2esta-doc/src/main/asciidoc/mca2estaCookbook/McaEsta-Migration_ETS-Workbook.adoc: Failed to parse source, Invalid type for treeprocessor extension: Java::OrgAsciidoctorExtension::Treeprocessor
```
Is my configuration wrong? And one more question: I was searching for the treeprocessor maven artifact but did not find it. Are all extensions already included in the core?

```
<plugin>
						<groupId>org.asciidoctor</groupId>
						<artifactId>asciidoctor-maven-plugin</artifactId>
						<version>1.5.2.1</version>
						<dependencies>
							<dependency>
								<groupId>org.asciidoctor</groupId>
								<artifactId>asciidoctorj-pdf</artifactId>
								<version>1.5.0-alpha.8</version>
							</dependency>
						</dependencies>
						<executions>
							<execution>
								<id>mca-esta-migration-docs</id>
								<phase>generate-resources</phase>
								<goals>
									<goal>process-asciidoc</goal>
								</goals>
								<configuration>
									<extensions>
										<extension>
											<className>org.asciidoctor.extension.Treeprocessor</className>
										</extension>
									</extensions>
									<attributes>
										<buildVersion>${project.version}</buildVersion>
									</attributes>
									<sourceDirectory>blabla
									</sourceDirectory>
									<outputDirectory>${project.build.directory}/generated-docs/
									</outputDirectory>
									<backend>html</backend>
									<doctype>book</doctype>
									<preserveDirectories>true</preserveDirectories>
								</configuration>
							</execution>
						</executions>
					</plugin>
```

**Comment by mojavelinux** [comment] 2015-07-09 09:39
> Are all extensions already included in the core?

Yes.

**Comment by robertpanzer** [comment] 2015-07-09 09:43
I think the problem is that you have to define the class name of your concrete extension implementation:
`<className>org.asciidoctor.extension.Treeprocessor</className>`

`org.asciidoctor.extension.Treeprocessor` is the base class for all Treeprocessors and your implementation must extend this class.
The `classname` element in your pom has to to contain the name of that subclass.

**Comment by bladnor** [comment] 2015-07-09 10:59
Aha. Looks like I misunderstood things. I was looking for something to render a directory tree structure and thought the treeprocessor is what I need. Meanwhile I have found Dan Allans link to https://github.com/allati/asciidoctor-extension-monotree. Thanks.

**Closed** 2015-08-19 20:19 UTC
Labels: bug
