### ISSUE TITLE
ClassCastException when parsing attributes

### ISSUE THREAD

**Issue by AFulgens** [asciidoctor/asciidoctorj#531] opened 2016-11-08 10:28 UTC
- AsciidoctorJ version: 1.5.3 (I know, I know, but I cannot upgrade yet)
- Issue with: `BlockProcessor#process(AbstractBlock, Reader, Map<String, Object>)`
- Issue is: `ClassCastException` when traversing keyset of last parameter called `attributes`

**Details:**
```
attributes.keySet().stream().forEach(System.out::println);
```
Will emit a `java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String` (there is a key which is `1`, apparently that's a `Long`; this key exists for every block).

This renders harder to do dynamic attribute matching, e.g.,
```
Pattern myPattern = Pattern.compile("some.*pattern");
attributes.entrySet().stream().filter(e -> myPattern.matches(e.getKey())).[...];
```
won't work.

Didn't test with newer AsciidoctorJ versions.

**Comment by robertpanzer** [comment] 2016-11-12 17:20
The observed behavior is correct and it should be fixed in the upcoming 1.6.0.
The Longs in the attribute map relate to the positional attributes of the block.

This means that at the moment you have to treat the keys as Objects if you want to iterate over them.

Closing this as duplicate of #450

**Closed by robertpanzer** 2016-11-12 17:20 UTC
