### ISSUE TITLE
Exception getting the blocks of a document

### ISSUE THREAD

**Issue by pmagon** [asciidoctor/asciidoctorj#270] opened 2015-01-12 16:40 UTC
When trying to get the blocks on a document:

    Document doc = asciidoctor.load(s, parameters) ;
    for (AbstractBlock b : doc.blocks())
    {
        ...
    }

With this document
        
    = Hello

    Test

    == WORLD

I get:

    Exception in thread "main" java.lang.ClassCastException: org.asciidoctor.ast.SectionImpl cannot be cast to org.jruby.RubyObject
	at org.asciidoctor.ast.AbstractBlockImpl.blocks(AbstractBlockImpl.java:52)
	at com.imtf.test.asciidoc.TestAsciiDoc.showDoc(TestAsciiDoc.java:301)
	at com.imtf.test.asciidoc.TestAsciiDoc.test6(TestAsciiDoc.java:342)
	at com.imtf.test.asciidoc.TestAsciiDoc.main(TestAsciiDoc.java:361)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

And this:

    = Hello

    Test

    test::
    This is a test

I get:

    Exception in thread "main" java.lang.ClassCastException: org.asciidoctor.ast.AbstractBlockImpl cannot be cast to org.jruby.RubyObject
	at org.asciidoctor.ast.AbstractBlockImpl.blocks(AbstractBlockImpl.java:52)
	at com.imtf.test.asciidoc.TestAsciiDoc.showDoc(TestAsciiDoc.java:301)
	at com.imtf.test.asciidoc.TestAsciiDoc.test6(TestAsciiDoc.java:342)
	at com.imtf.test.asciidoc.TestAsciiDoc.main(TestAsciiDoc.java:361)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by robertpanzer** [comment] 2015-04-07 13:33
Just confirmed that the following test fails on 1.5.2.
The problem seems to occur when the blocks are obtained twice:
```
    @Test
    public void should_get_all_blocks_as_AsciidoctorJ_AST_types() {
        Document document = asciidoctor.load(DOCUMENT, new HashMap<String, Object>());

        for (Object block: document.blocks()) {
            assertThat(block, instanceOf(AbstractBlock.class));
        }
        for (Object block: document.blocks()) {
            assertThat(block, instanceOf(AbstractBlock.class)); // ClassCastException occurs here
        }
    }
```

But the problem seems to be resolved with the current master and asciidoctorj-1.6.0 branch.

**Comment by mojavelinux** [comment] 2015-04-29 19:55
Let's mark the issue as fixed then in 1.5.3 and/or 1.6.0 (set the milestone). Then you can close. (It's helpful to set the metadata correctly when closing an issue to help others know when it was fixed).

**Comment by robertpanzer** [comment] 2015-04-29 20:21
I think  this will only be resolved with 1.6.0.

**Closed** 2015-08-19 20:20 UTC
Labels: bug

**Comment by oliviercailloux** [comment] 2017-08-23 17:46
Please consider adding some doc about this in your main README.
If I understand correctly, the branch 1.5 is almost unusable because of this bug, for parsing at least (parsing even a simple document fails).
I suppose most of your users, like me, won’t look at this closed bug before hitting the bug for themselves. 
Then I had to switch to the 1.6 version. (Which I didn’t use at start because of its “alpha” label.) Which, furthermore, has some incompatible types. ⇒ Quite a bit of time lost, easily avoidable had I knew about this bug beforehand.
Please consider recommending to your users to use 1.6.x despite the alpha mark, if they consider using asciidoctorj for its parsing functionality.

**Comment by mojavelinux** [comment] 2017-09-17 00:01
> Please consider recommending to your users to use 1.6.x despite the alpha mark, if they consider using asciidoctorj for its parsing functionality.

This is exactly what needs to be stated in the README. The 1.5 branch should be used strictly for conversion. Any extensions should be done using the 1.6 branch.

The alpha label is there because these APIs are still subject to change when you move between alpha versions. But the software itself is robust.
