### ISSUE TITLE
Packaging type is set to pom instead of jar in generated POM

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#481] opened 2016-07-14 02:49 UTC
The POM file generated by the publishing plugin incorrectly sets the packaging type to `pom` instead of `jar`. We previously had a patch to reverse the incorrect behavior in Gradle, but that patch seems to have been removed.

See the difference between the following two POM files (before and after the change):

* before: https://repo1.maven.org/maven2/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.pom
* after: https://repo1.maven.org/maven2/org/asciidoctor/asciidoctorj/1.5.4.1/asciidoctorj-1.5.4.1.pom

This also affects the 1.6.0 branch.

**Comment by mojavelinux** [comment] 2016-07-14 02:49
cc: @ancho

**Comment by robertpanzer** [comment] 2016-07-14 05:56
:-( I even did a test building a sample Maven project before releasing and it worked fine (not the asciidoctor-maven-plugin but a with a unit test that uses the AsciidoctorJ API).
Sorry, somehow this slipped through.

**Comment by mojavelinux** [comment] 2016-07-14 05:58
I completely understand. This is so hard to catch. I just happened to notice it because I was examining the pom against another pom. I really wish Gradle would fix this upstream because we shouldn't have to be fixing it in the first place. ¯\_(ツ)_/¯

**Comment by abelsromero** [comment] 2016-07-14 07:10
Don't worry Robert, this does not affect the maven plugin because the scope for Asciidoctorj is set to `compile` in the pom. The examples also work if we replace the version with 1.5.4.1.
But it makes me think about the plugin release, should we make a new release with this version (1.5.4.1) or do you want to do a 1.5.4.2 to fix it. Other than that, the only pending thing to release is this [PR](https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/226).

**Comment by mojavelinux** [comment] 2016-07-14 07:36
As you mentioned, I'm not sure it's a showstopper. It seems like Maven mostly ignores the package type when using a dependency. It's more that it is technically incorrect...so I don't think we need to rush to fix it. It just would be nice if was corrected for future releases.

**Comment by robertpanzer** [comment] 2016-07-14 08:04
I think as soon as we have a fix for this we should do a 1.5.4.2.
Then we can also release asciidoctorj-diagram 1.5.1.

**Comment by ancho** [comment] 2016-07-14 09:04
Just to get it right. The expected behaviour is a pom with packaging element with the value jar?

```
<modelVersion>4.0.0</modelVersion>
<groupId>org.asciidoctor</groupId>
<artifactId>asciidoctorj</artifactId>
<version>1.5.4.1</version>
<packaging>jar</packaging>
```

**Comment by robertpanzer** [comment] 2016-07-14 09:06
Maybe no packaging?
In https://repo1.maven.org/maven2/org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4.pom there is no packaging element.

**Comment by abelsromero** [comment] 2016-07-14 09:10
'jar 'is default packaging, so either adding it explicitly or leaving blank is efine.

**Comment by ancho** [comment] 2016-07-14 09:22
woah....this is annoying. adding a packaging definition to the pom produces two packaging tags, which invalidates the produced pom :(

```
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.asciidoctor</groupId>
  <artifactId>asciidoctorj</artifactId>
  <version>1.5.5.1</version>
  <packaging>jar</packaging>
  <packaging>pom</packaging>
```

**Comment by ancho** [comment] 2016-07-14 09:26
Found a solution by removing the packaging tag. Ugly...but valid fallback to default in this case.
I think this is worth a bug-report for the maven-publish plugin.

**Comment by ancho** [comment] 2016-07-14 10:01
Hmmm....thats weird. Can you please confirm, that a `./gradlew clean pTML` produces a valid pom in `asciidoctorj-core/build/publications/jars/pom-default.xml`?

Maybe the 'fix' is not necessary.

**Comment by ancho** [comment] 2016-07-14 10:07
I noticed a stale old `build/` directory in the root project. I removed it, and the pom was clean after running the command.

**Comment by abelsromero** [comment] 2016-07-14 10:18
I am using the `clean` + `generatePomFiles...` tasks on master and without any changes it generated a pom without <packaging> in `asciidoctorj-core/build/publications/jars` :confused: :question: 
In fact, @ancho's PR fails

**Comment by robertpanzer** [comment] 2016-07-14 10:22
I just did `./gradlew pTML` on the current master and indeed there was no packaging element.
Then I checked out the released commit 2e5bdece2072adacd99a553e9eab7ccdb36cee04 and built again. 
And for a release build I got the packaging element.

**Comment by ancho** [comment] 2016-07-14 10:25
o.O

**Comment by abelsromero** [comment] 2016-07-14 10:30
This is what I did:
- git clone ....
- cd asciidoctorj
- git checkout v1.5.4.1
- make sure no previous pom exists
- ./gradlew clean generatePom // pTML task fails during signature, which I guess is normal

And got a pom without `<packaging>` :ghost: 

Using Windows7 + Babun shell

**Comment by ancho** [comment] 2016-07-14 10:53
Yeah. Seams to correlate with the version what the maven-plugin does while generating the pom.
How bizarre. So sadly we need the fix.

@abelsromero The check task is successful but the bash test-asciidoctor-upstream.sh skript fails. See job details.

I'm not familiar with configuring travis. Is it possible to configure different commands for different branches?

For PR's a ./gradlew check should be sufficient.

**Comment by ancho** [comment] 2016-07-14 10:58
@abelsromero Jup. pTML tries to sign the pom and and archives for a release you can add -Pskip.signing to disable signing.

Or configure `signing.keyId`, `signing.password` and `signing.secretKeyRingFile` in your personal gradle.properties file to sign the artifacts with your gpg key

**Comment by robertpanzer** [comment] 2016-07-14 11:04
Hehe... just commented out my signing properties in ~/.gradle/gradle.properties and then the packaging element is not generated.
Somehow seems to be related to signing.
(This is really weird...)

**Comment by ancho** [comment] 2016-07-14 11:06
@abelsromero I tried the same steps....and got a pom with <packaging> tag.

* Debian 8 
* bash 4.3.30(1)-release 

```
./gradlew -v

------------------------------------------------------------
Gradle 2.14
------------------------------------------------------------

Build time:   2016-06-14 07:16:37 UTC
Revision:     cba5fea19f1e0c6a00cc904828a6ec4e11739abc

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_91 (Oracle Corporation 25.91-b14)
OS:           Linux 3.16.0-4-amd64 amd64
```

**Comment by ancho** [comment] 2016-07-14 11:08
@robertpanzer  Ok. We are getting closer...

**Comment by abelsromero** [comment] 2016-07-14 11:14
I'll look into it later this afternoon

**Comment by ancho** [comment] 2016-07-14 11:17
I found it. It's signed pom we are adding to the publication. I need to figure out how to publish the signed pom to bintray without adding it to the publication.

**Comment by abelsromero** [comment] 2016-07-14 20:05
> @abelsromero I tried the same steps....and got a pom with tag.

I set up the my gpg key on MacOS and I could get the `<packaging>` in the tag, but not in master.
Also, the PR worked for me.

I checked the files in my local repo to make sure.

**Closed** 2016-07-16 14:08 UTC
