### ISSUE TITLE
asciidoctorj-pdf exception 

### ISSUE THREAD

**Issue by mattadamson** [asciidoctor/asciidoctorj#456] opened 2016-05-03 20:09 UTC
Team,

I'm getting this exception converting an adoc file into a PDF. Is there a way to get more detailed information even with -X there is no more information available

[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:pr
ocess-asciidoc (output-pdf) on project swagger-doc-generator: Execution output-p
df of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc faile
d: (Errno::ENOENT) C:/Users/madamson/.m2/repository/org/asciidoctor/asciidoctorj
-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!D:/gems/addressable-2.4.
0/data/unicode.data -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc (output-pdf) on p
roject swagger-doc-generator: Execution output-pdf of goal org.asciidoctor:ascii
doctor-maven-plugin:1.5.3:process-asciidoc failed: (Errno::ENOENT) C:/Users/mada
mson/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.11/asciidoctorj
-pdf-1.5.0-alpha.11.jar!D:/gems/addressable-2.4.0/data/unicode.data
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBu
ild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:318)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:153)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
357)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution output-pd
f of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed
: (Errno::ENOENT) C:/Users/madamson/.m2/repository/org/asciidoctor/asciidoctorj-
pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!D:/gems/addressable-2.4.0
/data/unicode.data
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:115)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
        ... 19 more
Caused by: org.jruby.exceptions.RaiseException: (Errno::ENOENT) C:/Users/madamso
n/.m2/repository/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.11/asciidoctorj-pd
f-1.5.0-alpha.11.jar!D:/gems/addressable-2.4.0/data/unicode.data
        at org.jruby.RubyFile.initialize(org/jruby/RubyFile.java:370)
        at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1179)
        at RUBY.IDNA(C:/Users/madamson/.m2/repository/org/asciidoctor/asciidocto
rj-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/addressable-2.4.
0/lib/addressable/idna/pure.rb:330)
        at RUBY.Addressable(C:/Users/madamson/.m2/repository/org/asciidoctor/asc
iidoctorj-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/addressab
le-2.4.0/lib/addressable/idna/pure.rb:20)
        at RUBY.(root)(C:/Users/madamson/.m2/repository/org/asciidoctor/asciidoc
torj-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/addressable-2.
4.0/lib/addressable/idna/pure.rb:19)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)
        at RUBY.(root)(/C:/Users/madamson/.m2/repository/org/jruby/jruby-complet
e/1.7.23/jruby-complete-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems
/core_ext/kernel_require.rb:1)
        at RUBY.require(/C:/Users/madamson/.m2/repository/org/jruby/jruby-comple
te/1.7.23/jruby-complete-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygem
s/core_ext/kernel_require.rb:54)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)
        at RUBY.(root)(C:/Users/madamson/.m2/repository/org/asciidoctor/asciidoc
torj-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/addressable-2.
4.0/lib/addressable/idna.rb:24)
        at RUBY.(root)(/C:/Users/madamson/.m2/repository/org/jruby/jruby-complet
e/1.7.23/jruby-complete-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems
/core_ext/kernel_require.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)
        at RUBY.require(/C:/Users/madamson/.m2/repository/org/jruby/jruby-comple
te/1.7.23/jruby-complete-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygem
s/core_ext/kernel_require.rb:54)
        at RUBY.(root)(C:/Users/madamson/.m2/repository/org/asciidoctor/asciidoc
torj-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/addressable-2.
4.0/lib/addressable/uri.rb:20)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)
        at RUBY.(root)(/C:/Users/madamson/.m2/repository/org/jruby/jruby-complet
e/1.7.23/jruby-complete-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems
/core_ext/kernel_require.rb:1)
        at RUBY.require(/C:/Users/madamson/.m2/repository/org/jruby/jruby-comple
te/1.7.23/jruby-complete-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygem
s/core_ext/kernel_require.rb:54)
        at RUBY.(root)(C:/Users/madamson/.m2/repository/org/asciidoctor/asciidoc
torj-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/css_parser-1.3
.7/lib/css_parser.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)
        at RUBY.(root)(/C:/Users/madamson/.m2/repository/org/jruby/jruby-complet
e/1.7.23/jruby-complete-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems
/core_ext/kernel_require.rb:1)
        at RUBY.require(/C:/Users/madamson/.m2/repository/org/jruby/jruby-comple
te/1.7.23/jruby-complete-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygem
s/core_ext/kernel_require.rb:54)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)
        at RUBY.Document(C:/Users/madamson/.m2/repository/org/asciidoctor/asciid
octorj-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/prawn-svg-0.
21.0/lib/prawn/svg/document.rb:3)
        at RUBY.(root)(C:/Users/madamson/.m2/repository/org/asciidoctor/asciidoc
torj-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/prawn-svg-0.21
.0/lib/prawn/svg/document.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)
        at RUBY.(root)(/C:/Users/madamson/.m2/repository/org/jruby/jruby-complet
e/1.7.23/jruby-complete-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems
/core_ext/kernel_require.rb:1)
        at RUBY.require(/C:/Users/madamson/.m2/repository/org/jruby/jruby-comple
te/1.7.23/jruby-complete-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygem
s/core_ext/kernel_require.rb:54)
        at RUBY.(root)(C:/Users/madamson/.m2/repository/org/asciidoctor/asciidoc
torj-pdf/1.5.0-alpha.11/asciidoctorj-pdf-1.5.0-alpha.11.jar!/gems/prawn-svg-0.21
.0/lib/prawn-svg.rb:12)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)
        at RUBY.(root)(/C:/Users/madamson/.m2/repository/org/jruby/jruby-complet
e/1.7.23/jruby-complete-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems
/core_ext/kernel_require.rb:1)
        at RUBY.require(/C:/Users/madamson/.m2/repository/org/jruby/jruby-comple
te/1.7.23/jruby-complete-1.7.23.jar!/META-INF/jruby.home/lib/ruby/shared/rubygem
s/core_ext/kernel_require.rb:54)

Many thanks

**Comment by robertpanzer** [comment] 2016-05-03 20:32
Think it's a duplicate of
https://github.com/asciidoctor/asciidoctorj/issues/416
You can also upgrade to JRuby 1.7.24.

Cheers
Robert

Am Dienstag, 3. Mai 2016 schrieb mattadamson :

**Comment by mattadamson** [comment] 2016-05-05 09:17
thanks Robert, yes we can close this its fine upgrading the jruby dependency section

**Comment by robertpanzer** [comment] 2016-05-05 09:30
👍

**Closed by robertpanzer** 2016-05-05 09:30 UTC
