### ISSUE TITLE
NodeConverter returns value 0 for Inline literal `+{backtick}+` .

### ISSUE THREAD

**Issue by sanjaykumarbn** [asciidoctor/asciidoctorj#982] opened 2021-01-05 17:35 UTC
org.asciidoctor.jruby.ast.impl.NodeConverter returns value 0 when processing `+{backtick}+` .
Line 141
**case INLINE_CLASS:
ret = new PhraseNodeImpl(rubyObject);**
var8=RubyString value shownis 0.

**Comment by robertpanzer** [comment] 2021-01-08 11:03
Can you please provide some more detail and a reproducer for the behavior that you are observing?

I created a test for converting such a phrase node that you mentioned above in https://github.com/asciidoctor/asciidoctorj/pull/983 and it seems to work as expected.

**Comment by sanjaykumarbn** [comment] 2021-01-10 07:38
SORRY I forgot about the escape character.
The input as this : 
This is a \`+{backtick}+\'

Details :
for the input mentioned above
1st we fetch node.getDocument().getBlocks()
we get the paragraph nodde
2nd we fetch ((Block) block).getContent()
then we get the phrasenode
PhraseNode.class.cast(node)
and then when we fetch phraseNode.getReftext()
we get 0

**Comment by robertpanzer** [comment] 2021-01-10 17:11
It would be great if you could mention what you expect or what you want to get.
`getReftext()` should give you the reference text for a xref, i.e. for the PhraseNode representing `<<ref,Reference>>` a call to `node.getRefText()` should give you the string `"Reference"`.

If you want to get for your example the String `"{backtick}"` then you have to call `PhraseNode.getText()`.

**Comment by sanjaykumarbn** [comment] 2021-01-11 04:41
According to https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#literals-and-source-code
\`+{backtick}+\`  should be replaced by {backtick} .
phraseNode.getText()
and 
phraseNode.getReftext()
both returns back to me 0.

**Comment by robertpanzer** [comment] 2021-01-11 07:50
Sorry, I can't reproduce your description.
Contrary, I've created a test here that should show your expected behavior: https://github.com/asciidoctor/asciidoctorj/pull/983

If you are still facing issues please provide a reproducer, otherwise I cannot help.

**Comment by robertpanzer** [comment] 2021-04-11 10:12
Please provide an example that allows to reproduce the issue and reopen the ticket then.
Until then I'm closing this.

**Closed by robertpanzer** 2021-04-11 10:12 UTC
